name: Windows build

on:
  push:
    branches:
    - master
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  Windows-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Wonder
      run: echo xxx

    - uses: actions/cache@v2
      with:
        path: %LOCALAPPDATA%/vcpkg/archives
        key: ${{runner.os}}-vcpkg
     
    - name: Configure
      run: >
        cmake 
        -B ${{github.workspace}} 
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} 
        -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build ${{github.workspace}} --config ${{env.BUILD_TYPE}}

