name: build-windows

on:
  push:
    branches:
    - master
  pull_request:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      run: |
        vcpkg install libpng:x64-windows
        vcpkg install freetype:x64-windows
        vcpkg install libiconv:x64-windows
        
    - name: Build fontconfig
      run: vcpkg install fontconfig:x64-windows
 
