name: build-windows

on:
  push:
    branches:
    - master
  pull_request:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      run: |
        nuget install libpng_static
        nuget install freetype_static
        nuget install libiconv.lib
        
    - name: Build fontconfig
      run: |
        wget https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.13.94.tar.gz
        tar xvfz fontconfig-2.13.94.tar.gz
        cd fontconfig-2.13.94.tar.gz
 
